name:      day01
version:   1.0.0.0
license:   BSD3
author:    DonRyuDragoni
copyright: 2018 DonRyuDragoni

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  main:
    main:        Main.hs
    source-dirs: app
    dependencies:
      - day01

tests:
  test:
    main:        Main.hs
    source-dirs: test
    dependencies:
      - day01
      - test-framework
      - test-framework-hunit
      - HUnit
